version: "2"

services:
  postgres:
    image: postgres:11.4
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      POSTGRES_USER: opensanctions
      POSTGRES_PASSWORD: opensanctions

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis-data:/data

  ui:
    build: .
    command: gunicorn -t 900 -w 8 -b 0.0.0.0:8000 --log-level info --log-file - memorious.ui.views:app
    links:
      - redis
      - postgres
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    ports:
      - "8000:8000"
    environment:
      MEMORIOUS_DATASTORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      REDIS_URL: redis://redis:6379/0

  worker:
    build: .
    command: memorious process
    links:
      - postgres
      - redis
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    environment:
      MEMORIOUS_DATASTORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      REDIS_URL: redis://redis:6379/0
      FTM_STORE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
      WORKER_THREADS: 10
