name: interpol_red_notices
description: "[OSANC] Interpol Red Notices"
schedule: daily
pipeline:
  init:
    method: opensanctions.crawlers.interpol_red_notices:index
    params:
      url: 'http://www.interpol.int/notice/search/wanted/(offset)/%s'
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: parse
  parse:
    method: opensanctions.crawlers.interpol_red_notices:parse
