name: interpol_yellow_notices
description: "[OSANC] Interpol Yellow Notices"
schedule: daily
pipeline:
  init:
    method: seed
    params:
      url: "https://www.interpol.int/en/How-we-work/Notices/View-Yellow-Notices"
    handle:
      pass: fetch
  fetch:
    method: fetch
    params:
      http_rate_limit: 30
    handle:
      pass: index
  index:
    method: opensanctions.crawlers.interpol_yellow_notices:get_nationalities
    handle:
      pass: fetch_notices
  fetch_notices:
    method: fetch
    params:
      http_rate_limit: 30
    handle:
      pass: parse_nationalitywise_noticelist
  parse_nationalitywise_noticelist:
    method: opensanctions.crawlers.interpol_yellow_notices:parse_nationalitywise_noticelist
    handle:
      pass: fetch_notice
      fetch: fetch_notices_agewise
  fetch_notices_agewise:
    method: fetch
    params:
      http_rate_limit: 30
    handle:
      pass: parse_noticelist
  parse_noticelist:
    method: opensanctions.crawlers.interpol_yellow_notices:parse_noticelist
    handle:
      pass: fetch_notice
  fetch_notice:
    method: fetch
    params:
      http_rate_limit: 30
    handle:
      pass: parse_notice
  parse_notice:
    method: opensanctions.crawlers.interpol_yellow_notices:parse_notice
aggregator:
  method: ftm_load_aleph
